rm(list=ls(all.names = TRUE))
packages = c("jiebaR", "tm", "tmcn", "dplyr", "tidytext", "ggplot2", "wordcloud2", "rvest","stringr","dygraphs","knitr")
existing = as.character(installed.packages()[,1])
for(pkg in packages[!(packages %in% existing)]) install.packages(pkg)
# 載入library
library(rvest)
library(httr)
library(jiebaR)
library(tm)
library(tmcn)
library(dplyr)
library(tidytext)
library(stringr)
library(ggplot2)
library(dygraphs)
library(wordcloud2)
library(knitr)
library(kableExtra)
content_origin <- readLines("C:/Users/user/Desktop/aus.txt",encoding="UTF-8")
# 移除標點符號
content <- removePunctuation(content_origin)
cutter <- worker(bylines = F)
# 利用正規表達式移除數字
content <- str_remove_all(content, "[0-9]+?")
cutter <- worker(user = "C:/Users/user/Desktop/new_words.txt", stop_word = "C:/Users/user/Desktop/stop_words.txt", bylines = FALSE)
seg_words <- cutter[content]
txt_freq <- freq(seg_words)
txt_freq <- arrange(txt_freq, desc(freq))
head(txt_freq)
write.csv(txt_freq,"C:/Users/user/Desktop/aus_text_mining.csv")
#繪製文字雲
sydney <- read.csv("C:/Users/user/Desktop/sydney.csv",h=T,fileEncoding="UTF-8-BOM")
wordcloud2(sydney,size=0.5,shape='star',color='random-dark',backgroundColor="white")
Melbourne <- read.csv("C:/Users/user/Desktop/Melbourne.csv",h=T,fileEncoding="UTF-8-BOM")
wordcloud2(Melbourne,size=0.5,shape='star',color='random-dark',backgroundColor="white")